pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3-sapmachine-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Front-end-1') {
      agent {
        docker { image 'python:3.8-alpine3.19' }
      }
      steps {
        sh 'python3 -V'
      }
    }
  }
}
